apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      name: minecraft-pod
      labels:
        app: minecraft
        name: minecraft-pod
    spec:
      volumes:
        - name: world
          persistentVolumeClaim:
            claimName: minecraft-pv-claim
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          imagePullPolicy: Always
          volumeMounts:
            - name: world
              mountPath: /data
          ports:
            - name: game-port
              containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: MEMORY
              value: "4G"
          # resources:
          #   requests:
          #     cpu: 50m
          #     memory: 100Mi
          #   limits:
          #     cpu: 1
          #     memory: 2Gi