apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pv-claim
  labels:
    app: minecraft-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
